Map<String, String> egyptCitiesMap = {
  "القاهرة": "Cairo",
  "الجيزة": "Giza",
  "الإسكندرية": "Alexandria",
  "القليوبية": "Qalyubia",
  "البحيرة": "Beheira",
  "الغربية": "Gharbia",
  "الدقهلية": "Dakahlia",
  "الشرقية": "Sharqia",
  "كفر الشيخ": "Kafr El Sheikh",
  "المنوفية": "Monufia",
  "دمياط": "Damietta",
  "بورسعيد": "Port Said",
  "الإسماعيلية": "Ismailia",
  "السويس": "Suez",
  "شمال سيناء": "North Sinai",
  "جنوب سيناء": "South Sinai",
  "البحر الأحمر": "Red Sea",
  "الفيوم": "Fayoum",
  "بني سويف": "Beni Suef",
  "المنيا": "Minya",
  "أسيوط": "Assiut",
  "سوهاج": "Sohag",
  "قنا": "Qena",
  "الأقصر": "Luxor",
  "أسوان": "Aswan",
  "الوادي الجديد": "New Valley",
  "مطروح": "Matrouh",
};
